//============================ Health Routes =======================//

###
GET http://localhost:3001/health

//============================ Student Routes =======================//

###
POST http://localhost:3001/student/login
Content-Type: application/json

{
  "email": "fabio@gmail.com",
  "password": "fabio12345"
}

//============================ Score Routes =======================//

###
GET http://localhost:3001/score
Authorization: Bearer xxx
