version: '3.4'

networks:
  development:
    driver: bridge

services:

  api_admin_development:
    build:
      context: ./notas-admin
      dockerfile: Dockerfile
    networks:
      - development
    env_file:
      - .env.development
    ports:
      - 3000:3000
    volumes:
      - ./notas-admin:/api
    depends_on:
      - db_development

  api_aluno_development:
    build:
      context: ./notas-aluno
      dockerfile: Dockerfile
    networks:
      - development
    env_file:
      - .env.development
    ports:
      - 3001:3001
    volumes:
      - ./notas-aluno:/api
    depends_on:
      - db_development

  db_development:
    build:
      context: .
      dockerfile: db.Dockerfile
    env_file:
      - .env.development
    networks:
      - development
    # volumes: # uncomment to store volume
    #   - ./data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
