//============================ Health Routes =======================//

###
GET http://localhost:3000/health

//============================ Admin Routes =======================//

// Return: Admin[]
###
GET http://localhost:3000/admin
x-api-key: 2YmhGba76fQQa82jTfLokU1Ici9YJn


// Return: Admin (Error)
###
GET http://localhost:3000/admin/5dfc2b16-5cf8-4391-9632-8987eef9399a
x-api-key: 2YmhGba76fQQa82jTfLokU1Ici9YJn


// Return: Admin
###
GET http://localhost:3000/admin/3a37421b-dea7-42d0-a4ed-6e30e0d5e444
x-api-key: 2YmhGba76fQQa82jTfLokU1Ici9YJn


// Return: string
###
POST http://localhost:3000/admin
x-api-key: 2YmhGba76fQQa82jTfLokU1Ici9YJn
Content-Type: application/json

{
  "firstName": "Marcela",
  "lastName": "Rezende",
  "email": "marcela@gmail.com",
  "password": "12345abc"
}


// Return: string
###
PUT http://localhost:3000/admin/3a37421b-dea7-42d0-a4ed-6e30e0d5e444
x-api-key: 2YmhGba76fQQa82jTfLokU1Ici9YJn
Content-Type: application/json

{
  "lastName": "Castro"
}


// Return: string
###
DELETE http://localhost:3000/admin/3a37421b-dea7-42d0-a4ed-6e30e0d5e444
x-api-key: 2YmhGba76fQQa82jTfLokU1Ici9YJn


// Return: Object: { Admin, AccessToken }
###
POST http://localhost:3000/admin/login
Content-Type: application/json

{
  "email": "marcela@gmail.com",
  "password": "12345abc"
}

//============================ Student Routes =======================//

// Return: Student[]
###
GET http://localhost:3000/student
Authorization: Bearer xxx


// Return: string
###
POST http://localhost:3000/student
Content-Type: application/json
Authorization: Bearer xxx

{
  "firstName": "Fábio",
  "lastName": "Fernandes",
  "email": "fabio@gmail.com",
  "password": "fabio12345",
  "n1": 5,
  "n2": 8,
  "n3": 9,
  "n4": 7
}


// Return: string
###
POST http://localhost:3000/student/feae644c-16fd-4b8b-b350-e9edd9f5d4a2
Content-Type: application/json
Authorization: Bearer xxx

{
  "lastName": "de Assis",
  "n3": 1,
  "n2": 1
}
