//============================ Health Routes =======================//

###
GET http://localhost:3000/health

//============================ Admin Routes =======================//

###
GET http://localhost:3000/admin

###
GET http://localhost:3000/admin/5dfc2b16-5cf8-4391-9632-8987eef9399a


###
POST http://localhost:3000/admin
Content-Type: application/json

{
  "firstName": "Marcela",
  "lastName": "Rezende",
  "email": "marcela@gmail.com",
  "password": "12345abc"
}

###
PUT http://localhost:3000/admin/5dfc2b16-5cf8-4391-9632-8987eef9399a
Content-Type: application/json

{
  "lastName": "Castro"
}

###
DELETE http://localhost:3000/admin/5dfc2b16-5cf8-4391-9632-8987eef9399a

###
POST http://localhost:3000/admin/login
Content-Type: application/json

{
  "email": "marcela@gmail.com",
  "password": "12345abc"
}

//============================ Student Routes =======================//

###
GET http://localhost:3000/student
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDg1Njk4MDIsImV4cCI6MTY0ODY1NjIwMn0.qU9q7QomfnCrPOHsIHAgRc8LqcKYPLVp_DKZTeXh00w

###
POST http://localhost:3000/student
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDg1Njk4MDIsImV4cCI6MTY0ODY1NjIwMn0.qU9q7QomfnCrPOHsIHAgRc8LqcKYPLVp_DKZTeXh00w

{
  "firstName": "Lucio",
  "lastName": "Rodrigues",
  "n1": 1,
  "n2": 8,
  "n3": 9,
  "n4": 2
}

###
POST http://localhost:3000/student/98062c10-b635-4ad0-a51d-9079eab3156a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDg1Njk4MDIsImV4cCI6MTY0ODY1NjIwMn0.qU9q7QomfnCrPOHsIHAgRc8LqcKYPLVp_DKZTeXh00w

{
  "lastName": "Andrade",
  "n3": 1,
  "n2": 1
}
